let patientId=null,summaryData=null,lastBot='';
const $=id=>document.getElementById(id);
function toast(x){const t=$('toast');if(!t)return;t.textContent=x;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}
function scrollSection(id){const e=$(id);if(e)e.scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('.navItem').forEach(n=>n.classList.toggle('active',n.dataset.target===id))}
function theme(){document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'}
if(localStorage.theme==='dark')document.body.classList.add('dark');
function draft(){localStorage.caseDraft=$('caseText').value}
function clearDraft(){if(confirm('Clear the current case draft?')){$('caseText').value='';draft()}}
$('caseText').addEventListener('input',()=>{draft();$('dashInput').textContent=$('caseText').value.trim()?'Captured':'Waiting'})
function updateProgress(){let n=0;if(patientId)n++;if($('caseText').value.trim())n++;if(summaryData)n++;let p=Math.round(n/4*100);$('progressBar').style.width=p+'%';$('progressPct').textContent=p+'%';$('progressText').textContent=n+' of 4 steps complete';$('dashScore').textContent=summaryData?(summaryData.completeness_score||0)+'%':'0%';$('dashFlags').textContent=summaryData?(summaryData.red_flags||[]).length:0}
function continueCase(){scrollSection(patientId?'case':'registration')}
async function registerPatient(){const name=$('name').value.trim();if(!name)return toast('Enter patient name');if(!$('consent').checked)return toast('Consent is required');const r=await fetch('/api/patients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,age:$('age').value?Number($('age').value):null,gender:$('gender').value||null,phone:$('phone').value||null,language:$('language').value,consent:true})});const d=await r.json();if(!r.ok)return toast(d.detail||'Registration failed');patientId=d.id;$('dashPatient').textContent=name;$('pmsg').textContent='Patient registered ✓';toast('Patient registered');updateProgress();scrollSection('case')}
let recognition=null,listening=false;
function voice(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return toast('Speech recognition is not supported in this browser');if(listening){recognition&&recognition.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.continuous=true;recognition.interimResults=true;recognition.lang=($('language').value||'English')==='Hindi'?'hi-IN':'en-IN';recognition.onstart=()=>{listening=true;$('mic').textContent='⏹ Stop microphone';$('vmsg').textContent='Listening…'};recognition.onresult=e=>{let final='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';if(final){$('caseText').value+=($('caseText').value.trim()?' ':'')+final;draft();$('dashInput').textContent='Captured'}};recognition.onerror=e=>$('vmsg').textContent='Voice error: '+e.error;recognition.onend=()=>{listening=false;$('mic').textContent='🎙 Start microphone';$('vmsg').textContent='Mic ready • previous text is preserved';};recognition.start()}
async function analyze(){const text=$('caseText').value.trim();if(!patientId)return toast('Register the patient first');if(!text)return toast('Enter or speak the patient statement');$('amsg').textContent='Analyzing…';const r=await fetch('/api/cases/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,language:$('language').value})});summaryData=await r.json();renderSummary();$('amsg').textContent='Analysis complete ✓';updateProgress();renderReport();scrollSection('summarySection')}
function tags(a){return (a||[]).length?(a||[]).map(x=>'<span class="tag">'+x+'</span>').join(''):'<span class="hint">Not reported</span>'}
function renderSummary(){const s=summaryData;$('summary').innerHTML='<div class="summaryBlock"><b>Chief complaint</b><div>'+s.chief_complaint+'</div></div><div class="summaryBlock"><b>Symptoms</b><div>'+tags(s.symptoms)+'</div></div><div class="summaryBlock"><b>History</b><div>'+tags(s.history)+'</div></div><div class="summaryBlock"><b>Medications</b><div>'+tags(s.medications)+'</div></div><div class="summaryBlock"><b>Vitals</b><div>'+Object.entries(s.vitals||{}).map(([k,v])=>'<span class="tag">'+k+': '+v+'</span>').join('')||'<span class="hint">Not reported</span>'+'</div></div><div class="summaryBlock"><b>Detected language</b><div>'+s.detected_language+'</div></div><div class="summaryBlock"><b>Completeness</b><div class="score">'+s.completeness_score+'%</div></div>';$('safety').innerHTML=s.red_flags?.length?'<div class="danger"><b>⚠ Safety flags</b><br>'+s.red_flags.join(', ')+'<br><small>Seek appropriate clinical review; this demo does not diagnose.</small></div>':'<div class="safe"><b>✓ No configured red flag detected</b><br>Continue normal clinical review.</div>';$('questions').innerHTML=(s.missing_questions||[]).map(q=>'<div class="question">• '+q+'</div>').join('');updateProgress()}
function renderReport(){const s=summaryData,n=$('name').value||'Patient';$('preview').innerHTML='<div class="report"><div class="reportTop"><div class="brand"><div class="brandMark">A</div><div><b>ALGOMINDS</b><span>Patient Case-Taking Software</span></div></div><div class="reportTitle">CLINICAL CASE SUMMARY<br><small>'+new Date().toLocaleString()+'</small></div></div><div class="reportBody"><h2>'+n+'</h2><div class="summaryBlock"><b>Chief complaint</b><div>'+s.chief_complaint+'</div></div><div class="summaryBlock"><b>Symptoms</b><div>'+tags(s.symptoms)+'</div></div><div class="summaryBlock"><b>History</b><div>'+tags(s.history)+'</div></div><div class="summaryBlock"><b>Medications</b><div>'+tags(s.medications)+'</div></div><div class="summaryBlock"><b>Vitals</b><div>'+Object.entries(s.vitals||{}).map(([k,v])=>k+': '+v).join(' • ')+'</div></div><div class="summaryBlock"><b>Safety flags</b><div>'+(s.red_flags?.join(', ')||'None configured')+'</div></div><p><b>Clinical note:</b> '+s.clinical_note+'</p></div></div>';updateProgress()}
async function saveCSV(){if(!patientId||!summaryData)return toast('Register and analyze a case first');const r=await fetch('/api/cases/csv',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patient_id:patientId,raw_text:$('caseText').value,summary:summaryData,ayush:{}})});const d=await r.json();$('csvMsg').textContent=d.message||d.detail||'Saved';toast(d.message||'Saved to CSV')}
function downloadCSV(){window.location='/api/cases/csv/download'}
function pdf(){if(!summaryData)return toast('Generate the report first');const w=window.open('','_blank');w.document.write('<html><head><title>ALGOMINDS Patient Report</title><style>body{font:14px Arial;padding:35px;color:#17243a}.report{max-width:850px;margin:auto}.tag{display:inline-block;background:#eaf3ff;padding:5px 9px;border-radius:20px;margin:3px}.summaryBlock{padding:13px 0;border-bottom:1px solid #ddd}.summaryBlock>b{display:block;font-size:11px;color:#64748b;margin-bottom:5px}</style></head><body>'+$('preview').innerHTML+'</body></html>');w.document.close();w.print()}
function speak(t){if(!('speechSynthesis'in window))return toast('Speech synthesis unavailable');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
function readReport(){if(!summaryData)return toast('Generate the report first');speak('Patient '+($('name').value||'')+'. Chief complaint '+summaryData.chief_complaint+'. Symptoms '+(summaryData.symptoms||[]).join(', ')+'. History '+(summaryData.history||[]).join(', ')+'.')}
function readLast(){if(lastBot)speak(lastBot)}
function addChat(text,type){const d=document.createElement('div');d.className='bubble '+type;d.textContent=text;$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight}
function quickAsk(x){$('q').value=x;ask()}
function answer(q){const l=q.toLowerCase(),s=summaryData||{};if(l.includes('symptom'))return 'Reported symptoms: '+((s.symptoms||[]).join(', ')||'none captured')+'.';if(l.includes('know about me'))return 'Current case: '+(s.chief_complaint||'not analyzed')+'. Completeness is '+(s.completeness_score||0)+'%.';if(l.includes('doctor')||l.includes('see a'))return s.red_flags?.length?'A clinician should review this case promptly because configured safety flags were detected.':'A clinician should review the complete history and examination; this assistant cannot diagnose.';if(l.includes('report')||l.includes('simply'))return 'The case has been converted into a structured clinical summary. Ask the clinician to explain any medical finding you do not understand.';return 'I can explain the current case, symptoms, history, medicines, vitals and completeness. I cannot provide a diagnosis.'}
function ask(){const q=$('q').value.trim();if(!q)return;addChat(q,'user');$('q').value='';lastBot=answer(q);setTimeout(()=>addChat(lastBot,'bot'),180)}
function chatVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Speech recognition is not supported');const r=new R();r.lang='en-IN';r.onresult=e=>{$('q').value=e.results[0][0].transcript;ask()};r.start()}
async function ocr(){toast('OCR upload endpoint is available in the backend; browser preview will be added after file processing.')}
// restore draft
window.addEventListener('load',()=>{if(localStorage.caseDraft)$('caseText').value=localStorage.caseDraft;updateProgress();$('chat').innerHTML='';addChat('Hello. I can help explain the current patient case.','bot')})
